### ISSUE TITLE
Fix comparison between Position and tuple

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphas#374]
Finally fix:

```
Traceback (most recent call last):
  File "/home/arjan/Development/gaphor/.venv/lib/python3.10/site-packages/gaphas/tool/hover.py", line 24, in on_motion
    view.selection.hovered_item = find_item_at_point(view, (x, y))
  File "/home/arjan/Development/gaphor/.venv/lib/python3.10/site-packages/gaphas/tool/hover.py", line 29, in find_item_at_point
    return item or item_at_point(view, pos)
  File "/home/arjan/Development/gaphor/.venv/lib/python3.10/site-packages/gaphas/aspect/handlemove.py", line 180, in item_at_point
    item_distance = item.point(ix, iy)
  File "/home/arjan/Development/gaphor/gaphor/UML/classes/association.py", line 176, in point
    super().point(x, y), self._head_end.point(x, y), self._tail_end.point(x, y)
  File "/home/arjan/Development/gaphor/gaphor/diagram/presentation.py", line 241, in point
    d0 = super().point(x, y)
  File "/home/arjan/Development/gaphor/.venv/lib/python3.10/site-packages/gaphas/item.py", line 401, in point
    distance, _point = min(
TypeError: '<' not supported between instances of 'tuple' and 'Position'
```

NOTES:

**Version**
Version of Gaphas: 3.2.0

**Additional context**

**Comment by amolenaar** [comment]
Fixed by b382e3d080ccbc955a139af990a6c73fa406c94d
