### ISSUE TITLE
Gaphas Attribute Error

### ISSUE THREAD

**Issue by adamboduch** [gaphor/gaphas#6]
While working with components and connectors, I get the following:

<pre>
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/gaphas-0.5.0-py2.6.egg/gaphas/canvas.py", line 674, in update_now
    self.update_constraints(dirty_matrix_items)
  File "/usr/local/lib/python2.6/dist-packages/gaphas-0.5.0-py2.6.egg/gaphas/canvas.py", line 773, in update_constraints
    self._solver.solve()
  File "/usr/local/lib/python2.6/dist-packages/gaphas-0.5.0-py2.6.egg/gaphas/solver.py", line 621, in solve
    c.solve_for(wvar)
  File "/usr/local/lib/python2.6/dist-packages/gaphas-0.5.0-py2.6.egg/gaphas/constraint.py", line 492, in solve_for
    self._solve()
  File "/usr/local/lib/python2.6/dist-packages/gaphas-0.5.0-py2.6.egg/gaphas/constraint.py", line 513, in _solve
    sx, sy = self._line[0]
  File "/usr/local/lib/python2.6/dist-packages/gaphas-0.5.0-py2.6.egg/gaphas/canvas.py", line 1017, in __iter__
    return iter(self.pos)
  File "/usr/local/lib/python2.6/dist-packages/gaphas-0.5.0-py2.6.egg/gaphas/canvas.py", line 1008, in <lambda>
    self._point, self._get_value(),
  File "/usr/local/lib/python2.6/dist-packages/gaphas-0.5.0-py2.6.egg/gaphas/canvas.py", line 1004, in _get_value
    self._px, self._py = item.canvas.get_matrix_i2c(item).transform_point(x, y)
AttributeError: 'NoneType' object has no attribute 'get_matrix_i2c'
</pre>

**Comment by danyeaw** [comment]
@adamboduch I know this and https://github.com/gaphor/gaphas/issues/3 are out of the past, but do you have the code you were trying to run when you got these tracebacks? I would either like either reproduce and resolve these issues or close them.
